#!/bin/bash

# Function to display information about a subdomain
display_info() {
    local subdomain="$1"
    local domain="$2"

    # Use dig to get information about the subdomain
    result=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:')

    # Check if the result is empty
    if [ -z "$result" ]; then
        # echo "No information found for subdomain $subdomain"
        return
    fi

    # Extract relevant information using awk
    record_type=$(echo "$result" | awk '/IN[[:space:]]+[A-Z]+/{print $4}')
    destination=$(echo "$result" | awk '/IN[[:space:]]+[A-Z]+/{print $5}')

    # Check if destination is empty
    if [ -z "$destination" ]; then
        # echo "No information found for subdomain $subdomain"
        return
    fi

    # Display the information
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main script logic
if [ $# -eq 1 ]; then
    # When only the domain parameter is provided, display information for specific subdomains
    display_info www "$1"
    display_info lb-01 "$1"
    display_info web-01 "$1"
    display_info web-02 "$1"
elif [ $# -eq 2 ]; then
    # When both domain and subdomain parameters are provided, display information for the specified subdomain
    display_info "$2" "$1"
else
    # Handle incorrect number of parameters
    #echo "Usage: $0 domain [subdomain]"
	return
fi
