#!/usr/bin/env bash
# a script to transfer a file from client to a server

# must accept 4 parameters
if [ $# -ne 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Assign variables
PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"
# If less than 4 parameters are passed, transfer the file to the user's home directory

if [ "$#" -lt 4 ]; then
	DESTINATION="$HOME/${PATH_TO_FILE}"
else
	DESTINATION="${PATH_TO_FILE}"
fi

# Tranfer the file
scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i "${PATH_TO_SSH_KEY}" "${PATH_TO_FILE}" "${USERNAME}@${IP}:${DESTINATION}"
