#!/usr/bin/env bash
# script that installs nginx

# Update repositories
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

# Create a server block
echo "server {
    listen 80;
    listen [::]:80;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }
}" | sudo tee /etc/nginx/sites-available/default

# Enable the server block
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
# Create a test HTML file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Test the setup
# curl localhost

# Restart Nginx
sudo /etc/init.d/nginx restart
