#!/usr/bin/env bash
# script to redirect Nginx link

# Create a server block
echo "server {
    listen 80;
    listen [::]:80;

    server_name localhost;

    location = /redirect_me {
        return 301 \$scheme://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}" | sudo tee /etc/nginx/sites-available/default

# Enable the server block
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Restart Nginx
sudo /etc/init.d/nginx restart
