#!/usr/bin/env bash
# script to redirect Nginx link

# Create a configuration file for the redirection
echo "server {
    listen 80;
    server_name localhost;

    location = /redirect_me {
        return 301 \$scheme://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" | sudo tee /etc/nginx/sites-available/redirect_me.conf > /dev/null

# Enable the configuration
sudo ln -s /etc/nginx/sites-available/redirect_me.conf /etc/nginx/sites-enabled/

# Test the configuration and restart Nginx
sudo nginx -t && sudo systemctl restart nginx
