#!/usr/bin/env bash
# script to configure a brand new nginx machine and also write a redirect Nginx link

# Update repositories
sudo apt-get -y update
# Install Nginx
sudo apt-get -y install nginx

# Create a test HTML file
echo "Hello World!" | sudo tee /var/www/html/index.html
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
# custom 404 page
echo -e "Ceci n'est pas une page\n" | sudo tee /var/www/html/404.html

# Create a server block
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files \$uri \$uri/ /404.html; # Point to the custom 404 page
    }

    location = /redirect_me/ {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location = /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location = /404.html {
        root /var/www/html;
        internal;
    }

}" | sudo tee /etc/nginx/sites-available/default

# Enable the server block
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

sudo service nginx restart
