#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string
sudo apt-get update -y
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# custom 404 page
echo -e "Ceci n'est pas une page\n" | sudo tee /var/www/html/404.html

# Create a server block
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404; # Point to the custom 404 page
    }

    location = /redirect_me/ {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location = /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
}" | sudo tee /etc/nginx/sites-available/default

# Enable the server block
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

sudo service nginx restart
