#!/usr/bin/env bash
# script that installs nginx and sets up a 301 redirect and a custom 404 page

# Update repositories
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

# Prompt for domain name
read -p "Enter your domain name: " domain

# Create a server block
echo "server {
    listen 80;
    listen [::]:80;

    server_name localhost;

    location = /redirect_me {
        return 301 \$scheme://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /usr/share/nginx/html;
        internal;
    }
}" | sudo tee /etc/nginx/sites-available/default

# Enable the server block
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html

# Restart Nginx
sudo /etc/init.d/nginx restart
