#!/usr/bin/env bash
# This script configures a load balancer on a server

# update package
sudo apt update -y
# install the haproxy
sudo apt install haproxy -y

# configure frontedna nd backend
echo "
frontend obams_frontend
    bind *:80
    default_backend obams_backend

backend obams_backend
    balance roundrobin
    server 221986-web-01 3.85.41.84:80 check
    server 221986-web-02 54.90.17.105:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
