#!/usr/bin/env bash
# this script sets up and configures HAproxy on your lb-01 server

# install packages
sudo apt -y update
sudo apt -y upgrade
sudo apt -y install haproxy

# customize default configuration
echo "
global
    log /dev/log    local0
    log /dev/log    local1 notice
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server 221986-web-01 54.237.76.176:80 check
    server 221986-web-02 52.201.222.21:80 check
" | sudo tee /etc/haproxy/haproxy.cfg

# Step 3: Enable HAProxy to be managed via an init script
sudo systemctl enable haproxy

# Step 4: Ensure servers are configured with the right hostnames
sudo hostnamectl set-hostname 221986-web-01
echo "127.0.0.1 221986-web-01" | sudo tee -a /etc/hosts

sudo hostnamectl set-hostname 221986-web-02
echo "127.0.0.1 221986-web-02" | sudo tee -a /etc/hosts

# Step 5: Restart HAProxy and the servers for changes to take effect
sudo systemctl restart haproxy
sudo systemctl restart systemd-hostnamed
