#!/usr/bin/env bash
# Process and PID file
pid_file="/var/run/myscript.pid"

# check if /var/urn directory exists, create if not
if [ ! -d "/var/run" ]; then
	mkdir -p "/var/run"
fi

# Display PID and redirect output to the pid file
echo $$ > "$pid_file"

# create functions for signals
sigterm_handler()
{
	echo "I hate the kill command"
	rm -f "$pid_file"
	exit 0
}

# handle sigint
sigint_handler()
{
	echo "Y U no love me?!"
}

# handle SIGQuit
sigquit_handler()
{
	rm -f "$pid_file"
	exit 0
}

# Trap signals by calling functions
trap sigterm_handler SIGTERM
trap sigint_handler SIGINT
trap sigquit_handler SIGQUIT

# Keep loop running indefinitely
while true;
do
	# Display this message indefinitely
	echo "To infinity and beyond"
	sleep 2
done
