#!/usr/bin/env bash
# A script that manages the manage_my_process file

# use the case keyword to manage different patterns
case "$1" in
	start)
		./manage_my_process &
		echo $! > /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	stop)
		kill "$(cat /var/run/my_process.pid)"
		rm /var/run/my_process.pid
		echo "manage_my_process stopped"
		;;
	restart)
		$0 stop
		$0 start
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
