#!/usr/bin/env bash
# A script that manages the manage_my_process file

# use the case keyword to manage different patterns
tmp_file="/var/run/my_process.pid"

case "$1" in
	start)
		./manage_my_process &
		echo $! > "$tmp_file"
		echo "manage_my_process started"
		;;
	stop)
		kill "$(cat /var/run/my_process.pid)"
		rm -f "$tmp_file"
		echo "manage_my_process stopped"
		;;
	restart)
		kill "$(cat /var/run/my_process.pid)"
		rm -f "$tmp_file"
		./manage_my_process &
		echo $! > "$tmp_file"
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
