#!/usr/bin/env bash
# Script that kills/terminated a specified running process
# get the PID of the specified process
process=$(pgrep -f "4-to_infinity_and_beyond")
# kill the process
kill "$process"
