#!/usr/bin/env bash
# Script that displays To infinity and beyond indefinitely
# adds sleep 2 in each iteration
# prints I am invicible!!! when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERM
while true;
do
	echo "To infinity and beyond"
	sleep 2
done
