#!/usr/bin/env bash

# displaying the contents of the /etc/passwd file
# the etc 
# The /etc/passwd file is a system file on Unix and
# Unix-like operating systems
# It basically stores stores user account information.
# Each line in the file represents information about a single user,
# and the fields on each line are separated by colons (:).
# The traditional structure of the /etc/passwd file is as follows:

# username:password:UID:GID:GECOS:home_directory:shell

# username: This is the user's login name.
# password: Historically, this field used to contain the user's encrypted password.
# However, for security reasons, modern systems often store an 'x'
# character here and store the actual encrypted password 
#in the /etc/shadow file or a similar location.
# UID (User ID): This is a numerical value that uniquely identifies
# the user on the system.
# GID (Group ID): This is the numerical value that identifies
# the user's primary group.
# GECOS (General Electric Comprehensive Operating System):
# This field traditionally contained additional user information, 
# such as the user's full name and other details.
# However, it is often unused or contains arbitrary information.
# home_directory: This is the path to the user's home directory.
# shell: This is the user's default shell
# (the command interpreter that is started when the user logs in).

# SAMPLE: john:x:1001:1001:John Doe:/home/john:/bin/bash

while IFS=: read -r line
do
	# extract username, user_id and home directory using cut
	username=$(echo "$line" | cut -d: -f1)
	password=$(echo "$line" | cut -d: -f2)
	user_id=$(echo "$line" | cut -d: -f3)
	group_id=$(echo "$line" | cut -d: -f4)
	home_dir=$(echo "$line" | cut -d: -f6)
	shell=$(echo "$line" | cut -d: -f7)

	# DISPYAING THE SPECIFIED INFO ABOVE
	echo "The user $username is part of the $group_id gang, lives in $home_dir and rides $shell. $user_id's place is protected by the passcode $password, more info about the user here: $username"

done < /etc/passwd
