#!/usr/bin/env bash
#this script tells a story based on contents of /etc/passwd file

# SAMPLE: john:x:1001:1001:John Doe:/home/john:/bin/bash

FILENAME="/etc/passwd"
while IFS=: read -r username password userid groupid comment homedir cmdshell
do
 echo "The user $username is part of the $groupid gang, lives in $homedir and rides $cmdshell. $userid's place is protected by the passcode $password, more info about the user here: $comment"
done < $FILENAME
