#!/usr/bin/env bash
#this script tells a story based on contents of /etc/passwd file

# SAMPLE: john:x:1001:1001:John Doe:/home/john:/bin/bash

while IFS=: read -r line
do
	# extract username, user_id and home directory using cut
	username="$(echo "$line" | cut -d":" -f1)"
	password="$(echo "$line" | cut -d":" -f2)"
	user_id="$(echo "$line" | cut -d":" -f3)"
	group_id="$(echo "$line" | cut -d":" -f4)"
	home_dir="$(echo "$line" | cut -d":" -f6)"
	shell="$(echo "$line" | cut -d":" -f7)"

	# displaying contentsE
	echo "The user $username is part of the $group_id gang, lives in $home_dir and rides $shell. $user_id's place is protected by the passcode $password, more info about the user here: $username"

done < /etc/passwd
