#!/usr/bin/env bash
# this script parses an apache log file in the format:
# IP HTTP_CODE
# in a list format
# awk is the command instructed to be used

awk '{gsub(/\[|\]/, "", $4); print $1, $9}' apache-access.log
