#!/usr/bin/env bash
# this script parses an apache log file in the format:
# IP HTTP_CODE
# in a list format
# awk is the command instructed to be used

logfile="apache-access.log"
awk -F' ' '{ print $1, $9}' $logfile | sort | uniq -c|sort -nr
