#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# But at the 9th iteration, Hi is printed

i=0
while [ $i -lt 10 ];
do
	echo "Best School"
	if [ $i -eq 8 ]; then
		echo "Hi"
	fi

	((i++));
done
