#!/usr/bin/env bash
# This script is displaying "Best School" from 1 - 10
# But at the 4th iteration, bad luck is printed and 
# at 8th iteration good luck is printed

i=1
while [ $i -le 10 ];
do
	if [ $i -eq 4 ]; then
		echo "bad luck"
	elif [ $i -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi

	((i++));
done
