#!/usr/bin/env bash
# Bash script that displays:
# The content of the current directory
#In a list format
# Where only the part of the name after the first dash
# is displayed

LIST="$(ls ./)"

for file in $LIST;
do
	if [[ "$file" == *-* ]];then
		# use cut to extract name after dash
		new_file_name=$(echo "$file" | cut -d'-' -f2-)
		echo "$new_file_name"
	else
		# if no dash display name directly
		echo "$file"
	fi
done
