#!/usr/bin/env bash
# A bash script that changes my ip home ip address

hostfile="/etc/hosts"

cp "$hostfile"  ~/hosts.new
# modify local host to new address
sed -i '/localhost/s/127.0.0.1/127.0.0.2/' ~/hosts.new
# Append '8.8.8.8' after each line containing 'localhost'
sed -i '/localhost/a\8.8.8.8\ 	facebook.com' ~/hosts.new

# copy back the file to the original host
cp -f ~/hosts.new "$hostfile"
