#!/usr/bin/env bash
# script that run the whoami command under the user passed as an ament

# Check if the user provided an argument
if [ -z "$1" ]; then
    echo "Usage: "$0" <username>"
    exit 1
fi

# Run the 'whoami' command under the specified user
sudo -u "$1" whoami
