#!/usr/bin/env bash
# Change Nginx configuration to listen on port 8080

sudo sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default

# Change Nginx user to nginx
sudo sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf

# Restart Nginx
sudo service nginx restart
