#!/usr/bin/env bash
# Change Nginx configuration to listen on port 8080

# Change Nginx configuration to listen on port 8080
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default

# Change Nginx user to nginx
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf

# Adjust permissions for Nginx directories
chown -R nginx:nginx /etc/nginx /var/log/nginx

# Restart Nginx
sudo -u nginx service nginx start
