#!/usr/bin/env bash
# Bash script to gracefully start gunicorn

# Function to find the Gunicorn master PID
get_gunicorn_pid() {
  # Use ps to find processes with "gunicorn" in the command
  Gunicorn_PID=$(pgrep -f "gunicorn")

  # Check if any Gunicorn processes are found
  if [[ -z "$Gunicorn_PID" ]]; then
    echo "Error: No Gunicorn processes found!"
    exit 1
  fi
}

# Call the function to get the PID
get_gunicorn_pid

# Send HUP signal for graceful reload
echo "Sending HUP signal to Gunicorn master process (PID: $Gunicorn_PID) for graceful reload..."
kill -HUP "$Gunicorn_PID"

echo "Reload process initiated. New requests will be handled by workers with the updated code."

# ps aux | pgrep gunicorn | grep -v grep | awk '{print $2}' | xargs kill -HUP
